Frdq 57
Programmers-Only-Group/frontend pull request #38
Opened 2020-09-02 14:39 UTC by oskarwoj

2020-09-02 14:40 UTC, hayuna commented
<p>Total Coverage: <code>63.33</code></p>
<details><summary>Coverage report</summary>
<p>
<pre>
> frontend@0.1.0 test:coverage /home/runner/work/frontend/frontend
> npm test -- --coverage


> frontend@0.1.0 test /home/runner/work/frontend/frontend
> CI=true react-scripts test --env=jsdom "--coverage"

------------------------------------------|----------|----------|----------|----------|-------------------|
File                                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------------|----------|----------|----------|----------|-------------------|
All files                                 |    63.33 |    85.71 |       50 |    63.33 |                   |
 src                                      |        0 |      100 |        0 |        0 |                   |
  App.tsx                                 |        0 |      100 |        0 |        0 |                 4 |
  index.tsx                               |        0 |      100 |      100 |        0 |                 7 |
  react-app-env.d.ts                      |        0 |        0 |        0 |        0 |                   |
 src/components/ExampleStorybookComponent |        0 |      100 |        0 |        0 |                   |
  ExampleStorybookComponent.model.ts      |        0 |        0 |        0 |        0 |                   |
  ExampleStorybookComponent.tsx           |        0 |      100 |        0 |        0 |              9,10 |
 src/components/atoms/Button              |    90.91 |    90.91 |      100 |    90.91 |                   |
  Button.model.ts                         |        0 |        0 |        0 |        0 |                   |
  Button.tsx                              |    90.91 |    90.91 |      100 |    90.91 |                51 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/Header              |      100 |      100 |      100 |      100 |                   |
  Header.tsx                              |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/List                |        0 |      100 |        0 |        0 |                   |
  List.model.ts                           |        0 |        0 |        0 |        0 |                   |
  List.tsx                                |        0 |      100 |        0 |        0 |          12,13,16 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/ListItem            |        0 |        0 |        0 |        0 |                   |
  ListItem.model.ts                       |        0 |        0 |        0 |        0 |                   |
  ListItem.tsx                            |        0 |        0 |        0 |        0 |             11,12 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SnackBar            |      100 |      100 |      100 |      100 |                   |
  SnackBar.tsx                            |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SocialButton        |      100 |      100 |      100 |      100 |                   |
  SocialButton.model.ts                   |        0 |        0 |        0 |        0 |                   |
  SocialButton.tsx                        |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/styles                               |       75 |      100 |      100 |       75 |                   |
  GlobalStyles.tsx                        |        0 |      100 |      100 |        0 |                 4 |
  colors.ts                               |      100 |      100 |      100 |      100 |                   |
  devices.ts                              |      100 |      100 |      100 |      100 |                   |
  typography.ts                           |      100 |      100 |      100 |      100 |                   |
------------------------------------------|----------|----------|----------|----------|-------------------|
</pre>
</p>
</details>

2020-09-02 17:16 UTC, Krysik requested changes
* Text color should be #5D6371, instead #000000.
* Increase space between normal text and StyledLink.

2020-09-02 17:16 UTC, Krysik commented on src/components/atoms/ListItem/ListItem.styled.ts
> +    margin-right: 14px;
Margin between blue icon and text should be 8px

2020-09-02 17:55 UTC, Toumash commented on src/components/atoms/List/List.stories.tsx
> +      txt: 'Find support you need and help other people ',
Is this space really working? I didnt get it to work. My solution for ListItem here https://github.com/Programmers-Only-Group/frontend/pull/41

2020-09-03 08:23 UTC, hayuna commented
<p>Total Coverage: <code>63.33</code></p>
<details><summary>Coverage report</summary>
<p>
<pre>
> frontend@0.1.0 test:coverage /home/runner/work/frontend/frontend
> npm test -- --coverage


> frontend@0.1.0 test /home/runner/work/frontend/frontend
> CI=true react-scripts test --env=jsdom "--coverage"

------------------------------------------|----------|----------|----------|----------|-------------------|
File                                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------------|----------|----------|----------|----------|-------------------|
All files                                 |    63.33 |    85.71 |       50 |    63.33 |                   |
 src                                      |        0 |      100 |        0 |        0 |                   |
  App.tsx                                 |        0 |      100 |        0 |        0 |                 4 |
  index.tsx                               |        0 |      100 |      100 |        0 |                 7 |
  react-app-env.d.ts                      |        0 |        0 |        0 |        0 |                   |
 src/components/ExampleStorybookComponent |        0 |      100 |        0 |        0 |                   |
  ExampleStorybookComponent.model.ts      |        0 |        0 |        0 |        0 |                   |
  ExampleStorybookComponent.tsx           |        0 |      100 |        0 |        0 |              9,10 |
 src/components/atoms/Button              |    90.91 |    90.91 |      100 |    90.91 |                   |
  Button.model.ts                         |        0 |        0 |        0 |        0 |                   |
  Button.tsx                              |    90.91 |    90.91 |      100 |    90.91 |                51 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/Header              |      100 |      100 |      100 |      100 |                   |
  Header.tsx                              |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/List                |        0 |      100 |        0 |        0 |                   |
  List.model.ts                           |        0 |        0 |        0 |        0 |                   |
  List.tsx                                |        0 |      100 |        0 |        0 |          12,13,16 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/ListItem            |        0 |        0 |        0 |        0 |                   |
  ListItem.model.ts                       |        0 |        0 |        0 |        0 |                   |
  ListItem.tsx                            |        0 |        0 |        0 |        0 |             11,12 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SnackBar            |      100 |      100 |      100 |      100 |                   |
  SnackBar.tsx                            |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SocialButton        |      100 |      100 |      100 |      100 |                   |
  SocialButton.model.ts                   |        0 |        0 |        0 |        0 |                   |
  SocialButton.tsx                        |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/styles                               |       75 |      100 |      100 |       75 |                   |
  GlobalStyles.tsx                        |        0 |      100 |      100 |        0 |                 4 |
  colors.ts                               |      100 |      100 |      100 |      100 |                   |
  devices.ts                              |      100 |      100 |      100 |      100 |                   |
  typography.ts                           |      100 |      100 |      100 |      100 |                   |
------------------------------------------|----------|----------|----------|----------|-------------------|
</pre>
</p>
</details>

2020-09-03 20:52 UTC, hayuna commented
<p>Total Coverage: <code>53.33</code></p>
<details><summary>Coverage report</summary>
<p>
<pre>
> frontend@0.1.0 test:coverage /home/runner/work/frontend/frontend
> npm test -- --coverage


> frontend@0.1.0 test /home/runner/work/frontend/frontend
> CI=true react-scripts test --env=jsdom "--coverage"

------------------------------------------|----------|----------|----------|----------|-------------------|
File                                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------------|----------|----------|----------|----------|-------------------|
All files                                 |    53.33 |    85.71 |       40 |    53.33 |                   |
 src                                      |        0 |      100 |        0 |        0 |                   |
  App.tsx                                 |        0 |      100 |        0 |        0 |                 4 |
  index.tsx                               |        0 |      100 |      100 |        0 |                 7 |
  react-app-env.d.ts                      |        0 |        0 |        0 |        0 |                   |
 src/components/ExampleStorybookComponent |        0 |      100 |        0 |        0 |                   |
  ExampleStorybookComponent.model.ts      |        0 |        0 |        0 |        0 |                   |
  ExampleStorybookComponent.tsx           |        0 |      100 |        0 |        0 |              9,10 |
 src/components/atoms/Button              |    90.91 |    90.91 |      100 |    90.91 |                   |
  Button.model.ts                         |        0 |        0 |        0 |        0 |                   |
  Button.tsx                              |    90.91 |    90.91 |      100 |    90.91 |                51 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/Header              |        0 |      100 |        0 |        0 |                   |
  Header.tsx                              |        0 |      100 |        0 |        0 |              9,10 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/List                |        0 |      100 |        0 |        0 |                   |
  List.model.ts                           |        0 |        0 |        0 |        0 |                   |
  List.tsx                                |        0 |      100 |        0 |        0 |          12,13,16 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/ListItem            |        0 |        0 |        0 |        0 |                   |
  ListItem.model.ts                       |        0 |        0 |        0 |        0 |                   |
  ListItem.tsx                            |        0 |        0 |        0 |        0 |             11,12 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SnackBar            |      100 |      100 |      100 |      100 |                   |
  SnackBar.tsx                            |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SocialButton        |      100 |      100 |      100 |      100 |                   |
  SocialButton.model.ts                   |        0 |        0 |        0 |        0 |                   |
  SocialButton.tsx                        |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/styles                               |       50 |      100 |      100 |       50 |                   |
  GlobalStyles.tsx                        |        0 |      100 |      100 |        0 |                 4 |
  colors.ts                               |      100 |      100 |      100 |      100 |                   |
  devices.ts                              |        0 |      100 |      100 |        0 |                 1 |
  typography.ts                           |      100 |      100 |      100 |      100 |                   |
------------------------------------------|----------|----------|----------|----------|-------------------|
</pre>
</p>
</details>

2020-09-03 21:32 UTC, hayuna commented
<p>Total Coverage: <code>53.33</code></p>
<details><summary>Coverage report</summary>
<p>
<pre>
> frontend@0.1.0 test:coverage /home/runner/work/frontend/frontend
> npm test -- --coverage


> frontend@0.1.0 test /home/runner/work/frontend/frontend
> CI=true react-scripts test --env=jsdom "--coverage"

------------------------------------------|----------|----------|----------|----------|-------------------|
File                                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------------|----------|----------|----------|----------|-------------------|
All files                                 |    53.33 |    85.71 |       40 |    53.33 |                   |
 src                                      |        0 |      100 |        0 |        0 |                   |
  App.tsx                                 |        0 |      100 |        0 |        0 |                 4 |
  index.tsx                               |        0 |      100 |      100 |        0 |                 7 |
  react-app-env.d.ts                      |        0 |        0 |        0 |        0 |                   |
 src/components/ExampleStorybookComponent |        0 |      100 |        0 |        0 |                   |
  ExampleStorybookComponent.model.ts      |        0 |        0 |        0 |        0 |                   |
  ExampleStorybookComponent.tsx           |        0 |      100 |        0 |        0 |              9,10 |
 src/components/atoms/Button              |    90.91 |    90.91 |      100 |    90.91 |                   |
  Button.model.ts                         |        0 |        0 |        0 |        0 |                   |
  Button.tsx                              |    90.91 |    90.91 |      100 |    90.91 |                51 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/Header              |        0 |      100 |        0 |        0 |                   |
  Header.tsx                              |        0 |      100 |        0 |        0 |              9,10 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/List                |        0 |      100 |        0 |        0 |                   |
  List.model.ts                           |        0 |        0 |        0 |        0 |                   |
  List.tsx                                |        0 |      100 |        0 |        0 |          12,13,16 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/ListItem            |        0 |        0 |        0 |        0 |                   |
  ListItem.model.ts                       |        0 |        0 |        0 |        0 |                   |
  ListItem.tsx                            |        0 |        0 |        0 |        0 |             11,12 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SnackBar            |      100 |      100 |      100 |      100 |                   |
  SnackBar.tsx                            |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SocialButton        |      100 |      100 |      100 |      100 |                   |
  SocialButton.model.ts                   |        0 |        0 |        0 |        0 |                   |
  SocialButton.tsx                        |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/styles                               |       50 |      100 |      100 |       50 |                   |
  GlobalStyles.tsx                        |        0 |      100 |      100 |        0 |                 4 |
  colors.ts                               |      100 |      100 |      100 |      100 |                   |
  devices.ts                              |        0 |      100 |      100 |        0 |                 1 |
  typography.ts                           |      100 |      100 |      100 |      100 |                   |
------------------------------------------|----------|----------|----------|----------|-------------------|
</pre>
</p>
</details>

2020-09-05 11:37 UTC, oskarwoj commented
Color is set to #5D6371 and is working, only Storybook shows #000000. @Toumash  any ideas?
<img width="459" alt="screen" src="https://user-images.githubusercontent.com/66200850/92304261-a0253e80-ef7c-11ea-892d-5b4b20afbe94.PNG">

2020-09-05 14:16 UTC, hayuna commented
<p>Total Coverage: <code>48.48</code></p>
<details><summary>Coverage report</summary>
<p>
<pre>
> frontend@0.1.0 test:coverage /home/runner/work/frontend/frontend
> npm test -- --coverage


> frontend@0.1.0 test /home/runner/work/frontend/frontend
> CI=true react-scripts test --env=jsdom "--coverage"

------------------------------------------|----------|----------|----------|----------|-------------------|
File                                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------------|----------|----------|----------|----------|-------------------|
All files                                 |    48.48 |    85.71 |    36.36 |    48.48 |                   |
 src                                      |        0 |      100 |        0 |        0 |                   |
  App.tsx                                 |        0 |      100 |        0 |        0 |                 6 |
  index.tsx                               |        0 |      100 |      100 |        0 |                 7 |
  react-app-env.d.ts                      |        0 |        0 |        0 |        0 |                   |
 src/assets                               |        0 |        0 |        0 |        0 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/ExampleStorybookComponent |        0 |      100 |        0 |        0 |                   |
  ExampleStorybookComponent.model.ts      |        0 |        0 |        0 |        0 |                   |
  ExampleStorybookComponent.tsx           |        0 |      100 |        0 |        0 |              9,10 |
 src/components/atoms/Button              |    90.91 |    90.91 |      100 |    90.91 |                   |
  Button.model.ts                         |        0 |        0 |        0 |        0 |                   |
  Button.tsx                              |    90.91 |    90.91 |      100 |    90.91 |                51 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/Header              |        0 |      100 |        0 |        0 |                   |
  Header.tsx                              |        0 |      100 |        0 |        0 |             10,11 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/List                |        0 |      100 |        0 |        0 |                   |
  List.model.ts                           |        0 |        0 |        0 |        0 |                   |
  List.tsx                                |        0 |      100 |        0 |        0 |          13,14,17 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/ListItem            |        0 |        0 |        0 |        0 |                   |
  ListItem.model.ts                       |        0 |        0 |        0 |        0 |                   |
  ListItem.tsx                            |        0 |        0 |        0 |        0 |             11,12 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SnackBar            |      100 |      100 |      100 |      100 |                   |
  SnackBar.tsx                            |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/components/atoms/SocialButton        |      100 |      100 |      100 |      100 |                   |
  SocialButton.model.ts                   |        0 |        0 |        0 |        0 |                   |
  SocialButton.tsx                        |      100 |      100 |      100 |      100 |                   |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/pages/Home                           |        0 |      100 |        0 |        0 |                   |
  Home.tsx                                |        0 |      100 |        0 |        0 |             19,20 |
  data.ts                                 |        0 |      100 |      100 |        0 |                 1 |
  index.ts                                |        0 |        0 |        0 |        0 |                   |
 src/styles                               |       50 |      100 |      100 |       50 |                   |
  GlobalStyles.tsx                        |        0 |      100 |      100 |        0 |                 4 |
  colors.ts                               |      100 |      100 |      100 |      100 |                   |
  devices.ts                              |        0 |      100 |      100 |        0 |                 1 |
  typography.ts                           |      100 |      100 |      100 |      100 |                   |
------------------------------------------|----------|----------|----------|----------|-------------------|
</pre>
</p>
</details>

2020-09-06 17:37 UTC, closed without merging